# Generated by Django 5.0.7 on 2024-08-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
