# Generated by Django 5.0.7 on 2024-08-01 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField(max_length=100, null=True)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
