# Generated by Django 5.0.7 on 2024-08-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_post_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_like',
            new_name='Postlike',
        ),
    ]
